name: CI

on: [push]

jobs:
  test:
    runs-on: self-hosted
    container:
      image: vogonchar/tag_creator:tagname
    steps:
      - uses: actions/checkout@v4
      - name: pytest
        run: python -m pytest
      - name: mypy
        run: python -m mypy -p tag_creator --config .mypy.ini
      - name: flake8
        run: flake8 .
