name: On-commit

on:
  pull_request:
    types:
      - synchronize
      - edited

jobs:
  code-test:
    if: github.event.action == 'synchronize'
    runs-on: self-hosted
    container:
      image: vogonchar/tag_creator:latest
    steps:
      - name: Cleanup
        run: find ${GITHUB_WORKSPACE} -mindepth 1 -delete
      - uses: actions/checkout@v4
      - name: pytest
        run: python -m pytest
      - name: mypy
        run: python -m mypy -p tag_creator --config .mypy.ini
      - name: flake8
        run: flake8 .
  commit-lint:
    runs-on: self-hosted
    container:
      image: registry.hub.docker.com/library/node:alpine
    steps:
      - name: Cleanup
        run: find ${GITHUB_WORKSPACE} -mindepth 1 -delete
      - uses: actions/checkout@v4
      - name: lint
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: |
          npm install --save-dev @commitlint/config-conventional @commitlint/cli
          echo -e $TITLE | npx commitlint
  build:
    needs: [commit-lint, code-test]
    runs-on: self-hosted
    container:
      image: vogonchar/tag_creator:latest
    steps:
      - name: Cleanup
        run: find ${GITHUB_WORKSPACE} -mindepth 1 -delete
      - uses: actions/checkout@v4
      - name: build
        run: |
          git config --global --add safe.directory '*'
          git config --global user.email "test@mycomp.org"
          git config --global user.name "Bot"
          python -m build
          pip install .
          git fetch --all
          git checkout main
          python -m tag_creator --create_new_tag --dry_run --release_branch main --tag_prefix="v"
